export const STATUS = {
  RENDER_ACCA: "RENDER_ACCA",
  RENDER_ACCA_COMPLETE: "RENDER_ACCA_COMPLETE",
  RENDER_ACCA_MC_VAYVON: "RENDER_ACCA_MC_VAYVON",
  RENDER_ACCA_MC_VAYVON_COMPLETE: "RENDER_ACCA_MC_VAYVON_COMPLETE",
  RENDER_ACCA_MC_CARD: "RENDER_ACCA_MC_CARD",
  RENDER_ACCA_MC_CARD_COMPLETE: "RENDER_ACCA_MC_CARD_COMPLETE",
  CONVERT_IMG_PDF: "CONVERT_IMG_PDF",
  CONVERT_IMG_PDF_COMPLETE: "CONVERT_IMG_PDF_COMPLETE",
};
